server:
  port: 8083

spring:
  application:
    name: vitalreports

eureka:
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
