server:
  port: 8088

spring:
  application:
    name: apigateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: iot-service
          order: -10
          uri: http://iot-service:8082
          predicates:
            - Path=/api/sensordata/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        - id: chatbotbackend
          order: 1
          uri: lb://chatbotbackend
          predicates:
            - Path=/api/bot/**
          filters:
            - StripPrefix=0

        - id: vitalreports
          order: 2
          uri: lb://vitalreports
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=0

        - id: mainservice
          order: 100
          uri: lb://mainservice
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discoveryserver:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
