server:
  port: 8088

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: iot-service
          uri: ${IOT_SERVICE_URL:http://iot-service:8082}
          predicates:
            - Path=/api/iot/**

        - id: chatbotbackend
          uri: ${CHATBOT_SERVICE_URL:http://chatbotbackend:8081}
          predicates:
            - Path=/api/bot/**

        - id: vitalreports
          uri: ${VITALREPORTS_SERVICE_URL:http://vitalreports:8083}
          predicates:
            - Path=/api/reports/**

        - id: mainservice
          uri: ${MAIN_SERVICE_URL:http://mainservice:8080}
          predicates:
            - Path=/api/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
    org.springframework.web.reactive: INFO
